title: "Andrew Sayre"
tagline: "Portfolio and latest updates"
description: "Portfolio and latest updates from Andrew Sayre, a software engineering leader building impactful and innovative products that improve people's lives"
baseurl: ""
url: "http://andrewsayre.github.io"
author: andrewsayre
logo: /assets/images/profile.jpg
social:
  links:
    - https://www.linkedin.com/in/andrewsayre/
    - https://github.com/andrewsayre
    - https://bsky.app/profile/andrewsayre.com

# Build settings
plugins:
  - jekyll-feed
  - jekyll-seo-tag

position_date_format: '%b %Y'
presentation_date_format: '%b %d, %Y'

collections:
  posts:
    output: true
    permalink: /posts/:year/:month/:day/:title

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/